testdb:
    image: mongo
    hostname: testdb
    expose:
        - "27017"
    restart: always

series-microservice:
    build: ./series-microservice
    hostname: mongo-express
    links:
        - testdb:testdb
    ports:
        - "3000:3000"
    restart: always
    environment:
        - MONGO_HOST=testdb
        - MONGO_PORT=27017
